import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const pkgPath = path.resolve(__dirname, '../package.json');
const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));

console.log("Debug: Package.json content:", JSON.stringify(pkg, null, 2));

const coreVersion = pkg.p47h?.coreVersion;

if (!coreVersion) {
    console.error("❌ Error: p47h.coreVersion not found in package.json");
    process.exit(1);
}

const content = `// Auto-generated by scripts/update-version.js
export const REQUIRED_CORE_VERSION = "${coreVersion}";
`;

const destPath = path.resolve(__dirname, '../src/version.ts');
fs.writeFileSync(destPath, content);

console.log(`✅ Generated src/version.ts with REQUIRED_CORE_VERSION = ${coreVersion}`);
